Updates

diff --git a/.cloudbees/workflows/blackduck-scan-public-image.yaml b/.cloudbees/workflows/blackduck-scan-public-image.yaml
--- a/.cloudbees/workflows/blackduck-scan-public-image.yaml
+++ b/.cloudbees/workflows/blackduck-scan-public-image.yaml
@@ -23,16 +23,22 @@ jobs:
         uses: docker://docker:24.0.6-dind
         shell: sh
         run: |
-          dockerd-entrypoint.sh &
-          until docker info >/dev/null 2>&1; do
-          echo "Waiting for Docker daemon..."
+            dockerd-entrypoint.sh &
+            echo "Waiting for Docker daemon to start..."
+            for i in $(seq 1 30); do
+            if docker info >/dev/null 2>&1; then
+            echo "Docker is ready!"
+            break
+            fi
+            echo "Waiting... ($i/30)"
             sleep 2
-          done
-
-          # Pull the image and save to tar
-          docker pull ubuntu:oracular-20240811.1
-          docker save -o ubuntu_latest.tar ubuntu:oracular-20240811.1
-
+            done
+            if ! docker info >/dev/null 2>&1; then
+            echo "Docker daemon failed to start in time."
+            exit 1
+                fi
+            docker pull ubuntu:oracular-20240811.1
+            docker save -o ubuntu_latest.tar ubuntu:oracular-20240811.1
       - name: Run Black Duck hybrid scan
         uses: cloudbees-io/blackduck-sca-scan-dependency@apr
         with:
